<a href="https://colab.research.google.com/github/ShahKhalid1234/Python/blob/main/NumpyPandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
#numpy
import numpy as n
list1=[[1,4,5],[6,7,8],[9,4,5]]
array=n.array(list1)  #list as argument to make it numpy array
print(array)
result=2+array

#print(result)
b1=[[1,4,5],[6,7,5],[7,9,7]]
b1=n.array(b)
print(b1)


reshaped=b1.reshape(3,2)
print(reshaped)
print(b1)
print(array[1:2])
degree=b1**2      #element wise squaring
print(degree)

[[1 4 5]
 [6 7 8]
 [9 4 5]]
[[1 4 5]
 [6 7 5]]
[[1 4]
 [5 6]
 [7 5]]
[[1 4 5]
 [6 7 5]]
[[6 7 8]]
[[ 1 16 25]
 [36 49 25]]


In [8]:
import pandas as pd
frame={'name':['Khalid','Suhail','aijaz']
       ,'age':[25,23,25]
       ,'city':['ang','ang','kup']}

In [15]:
l=pd.DataFrame(frame)

In [12]:
print(l)

     name  age city
0  Khalid   25  ang
1  Suhail   23  ang
2   aijaz   25  kup


In [17]:
#column access
print(l['age'])

0    25
1    23
2    25
Name: age, dtype: int64


In [19]:
print(l.iloc[1])      #using.ilocto find a particular row by index

name    Suhail
age         23
city       ang
Name: 1, dtype: object


In [20]:
print(l.iloc[0:1])      #using.iloc to find a particular row by index in range

     name  age city
0  Khalid   25  ang


In [23]:
print(l.loc[l['name']=='Suhail'])

     name  age city
1  Suhail   23  ang


In [55]:
print(l.rename(columns={'city':'address'})) #rename a particular column

     name  age address
0  Khalid   25     ang
1  Suhail   23     ang
2   aijaz   25     kup


In [65]:
l.drop(columns=['age']) #delete a column



name city
0  Khalid  ang
1  Suhail  ang
2   aijaz  kup

In [26]:
#series

import pandas as pd

Marks= [10, 20, 30, 40, 50]
subject = ['A', 'B', 'C', 'D', 'E']
Reportcard = pd.Series(Marks, index=subject)

print(Reportcard)

A    10
B    20
C    30
D    40
E    50
dtype: int64


In [36]:
Reportcard+=5      #arithmetic operation on series

In [35]:
print('After your +5 your result\n',(Reportcard))


After your +5 your result
 A    15
B    25
C    35
D    45
E    55
dtype: int64


In [43]:

#fIltering series
rollno1=series[Reportcard>30]

In [44]:
print(rollno1)

C    30
D    40
E    50
dtype: int64


In [46]:
totalmarks=Reportcard.sum()
print(totalmarks)

200


In [49]:
print(Reportcard.sum())


200


In [50]:
print(Reportcard.mean())

40.0


In [52]:
print(Reportcard.max())

60
